behaviors:
  Pyramids:
    hyperparameters:
      batch_size: 256
      beta: 0.01
      buffer_size: 5120
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0004
      learning_rate_schedule: linear
      num_epoch: 4
    keep_checkpoints: 5
    max_steps: 7000000
    network_settings:
      hidden_units: 512
      normalize: false
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      curiosity:
        gamma: 0.99
        learning_rate: 0.0005
        network_settings:
          hidden_units: 256
        strength: 0.02
      extrinsic:
        gamma: 0.99
        strength: 1.0
    summary_freq: 30000
    time_horizon: 128
    trainer_type: ppo
