behaviors:
behaviors:
  Hallway:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 25600
      learning_rate: 0.0005
      beta: 0.04
      epsilon: 0.35
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000